# Corpus pipeline as Nix derivations.
#
# Three layers:
#   1. Image downloads — one FOD per unique URL via corpus-fetch binary
#   2. Analysis runs   — sandboxed derivations with GPU access (Python + models → JSON)
#   3. Corpus tests    — pure derivations (Rust tests over analysis results)
#
# Nix content-addressing handles cache invalidation: changing a model.py
# automatically invalidates downstream derivations.
{
  pkgs,
  lib,
  pythonEnvs,
  craneLib,
  rustCommonArgs,
}:

let
  # Import corpus manifest (pure data).
  corpusManifest = import ../analysis/corpus.nix;

  # Manifest as JSON file for Rust consumption (set via CORPUS_MANIFEST env var).
  corpusManifestJson = pkgs.writeText "corpus.json" (builtins.toJSON corpusManifest);

  # Load pre-computed URL hashes (generated by `just corpus-hash`).
  # Flat map: URL → "sha256-..." SRI hash.
  corpusHashesFile = ../analysis/corpus-hashes.json;
  corpusHashes = builtins.fromJSON (builtins.readFile corpusHashesFile);

  # Build corpus-fetch binary via crane.
  corpusFetchBin = craneLib.buildPackage (
    rustCommonArgs
    // {
      pname = "corpus-fetch";
      cargoExtraArgs = "--features corpus-test -p chronoscope-analysis --bin corpus-fetch";
      cargoArtifacts = craneLib.buildDepsOnly (
        rustCommonArgs
        // {
          pname = "corpus-fetch-deps";
          cargoExtraArgs = "--features corpus-test -p chronoscope-analysis";
        }
      );
      doCheck = false;
    }
  );

  # One FOD per unique URL. The corpus-fetch binary handles Reddit gallery
  # resolution inside the sandbox — no ephemeral CDN URLs leak into hashes.
  fetchCorpusUrl =
    url: hash:
    pkgs.stdenvNoCC.mkDerivation {
      name = "corpus-${builtins.hashString "sha256" url}";
      outputHashMode = "recursive";
      outputHashAlgo = "sha256";
      outputHash = hash;
      nativeBuildInputs = [
        corpusFetchBin
        pkgs.cacert
      ];
      SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
      buildCommand = ''
        corpus-fetch "${url}" "$out"
      '';
    };

  # Deduplicated URL → derivation map.
  urlDerivations = lib.mapAttrs fetchCorpusUrl corpusHashes;

  # Link farm: entry ID → specific file within URL's FOD.
  # Reddit gallery entries index into a multi-file FOD (0, 1, 2, ...);
  # direct URL entries always use index 0.
  corpusImages = pkgs.linkFarm "chronoscope-corpus-images" (
    lib.mapAttrsToList (
      id: entry:
      let
        fod = urlDerivations.${entry.url};
        index = entry.reddit_index or 0;
      in
      {
        name = id;
        path = "${fod}/${toString index}";
      }
    ) corpusManifest.images
  );

  # GPU-aware analysis derivation.
  #
  # IMPORTANT: GPU sandbox configuration
  # =====================================
  # This derivation needs GPU access for SAM3/DINOv3 inference. The Nix
  # sandbox stays intact (filesystem isolation preserved) — only GPU devices
  # are exposed to the build:
  #
  # Linux builder configuration (nix.conf):
  #   extra-sandbox-paths = /dev/nvidia0 /dev/nvidiactl /dev/nvidia-uvm /run/opengl-driver
  #   system-features = cuda
  #
  # Darwin: sandbox is off by default on macOS. Metal/MPS access works without
  # special configuration. TODO: design __sandboxProfile that enables sandbox
  # but grants Metal/MPS GPU access for filesystem isolation.
  analysisResults = pkgs.stdenv.mkDerivation (
    pythonEnvs.modelEnv
    // {
      pname = "chronoscope-analysis-results";
      version = "0.1.0";

      nativeBuildInputs = [ pythonEnvs.analysisEnv ];

      src = pythonEnvs.analysisSrc;

      # On Linux, require CUDA-capable builder.
      requiredSystemFeatures = lib.optionals pkgs.stdenv.hostPlatform.isLinux [ "cuda" ];

      buildPhase = ''
        runHook preBuild

        # stdenv may set SSL_CERT_FILE; we're fully offline so TLS is unnecessary.
        unset SSL_CERT_FILE

        # run_local.py reads paths from stdin, writes JSON lines to stdout.
        # corpusImages is a link farm (entry-id → FOD file); find -L follows
        # symlinks so basenames (= entry IDs) are preserved in the output.
        find -L ${corpusImages} -type f | sort | python run_local.py > results.jsonl

        runHook postBuild
      '';

      installPhase = ''
        runHook preInstall
        mkdir -p $out
        cp results.jsonl $out/
        runHook postInstall
      '';
    }
  );

  # Corpus test derivation — pure, no GPU needed.
  # Runs Rust corpus tests against pre-computed analysis results.
  # Reuses rustCommonArgs (from rust.nix) to avoid duplicating build deps.
  corpusTests = craneLib.cargoTest (
    let
      commonArgs = rustCommonArgs // {
        pname = "chronoscope-corpus-tests";
        ANALYSIS_RESULTS = analysisResults;
        CORPUS_MANIFEST = corpusManifestJson;
        cargoExtraArgs = "--features corpus-test -p chronoscope-analysis --test corpus_tests";
      };
    in
    commonArgs
    // {
      cargoArtifacts = craneLib.buildDepsOnly commonArgs;
      doInstallCargoArtifacts = false;
      # Output test report instead of archiving the target directory.
      # The test binary is fast (reads pre-computed JSON), so re-running
      # it in the install phase is cheap.
      installPhaseCommand = ''
        mkdir -p $out
        find target/release/deps -name 'corpus_tests-*' -type f -executable \
          -exec {} --color never \; 2>&1 | tee $out/test-report.txt
      '';
    }
  );

in
{
  inherit
    corpusImages
    analysisResults
    corpusTests
    corpusFetchBin
    corpusManifestJson
    ;
}
