# Corpus images as Nix derivations: one FOD per unique URL, fetched by the
# corpus-fetch binary, assembled into a link farm keyed by entry id.
#
# These are the photographs the vision pipeline develops against. The GPU
# derivation that once ran analysis over them, and the Rust tests that asserted
# on its output, are in git history: both were written against a schema the
# vision crate replaces.
{
  pkgs,
  lib,
  craneLib,
  rustCommonArgs,
}:

let
  # Import corpus manifest (pure data).
  corpusManifest = import ../analysis/corpus.nix;

  # Manifest as JSON file for Rust consumption (set via CORPUS_MANIFEST env var).
  corpusManifestJson = pkgs.writeText "corpus.json" (builtins.toJSON corpusManifest);

  # Load pre-computed URL hashes (generated by `just corpus-hash`).
  # Flat map: URL → "sha256-..." SRI hash.
  corpusHashesFile = ../analysis/corpus-hashes.json;
  corpusHashes = builtins.fromJSON (builtins.readFile corpusHashesFile);

  # Build corpus-fetch binary via crane.
  corpusFetchBin = craneLib.buildPackage (
    rustCommonArgs
    // {
      pname = "corpus-fetch";
      cargoExtraArgs = "--features corpus -p chronoscope-analysis --bin corpus-fetch";
      cargoArtifacts = craneLib.buildDepsOnly (
        rustCommonArgs
        // {
          pname = "corpus-fetch-deps";
          cargoExtraArgs = "--features corpus -p chronoscope-analysis";
        }
      );
      doCheck = false;
    }
  );

  # One FOD per unique URL. The corpus-fetch binary handles Reddit gallery
  # resolution inside the sandbox — no ephemeral CDN URLs leak into hashes.
  fetchCorpusUrl =
    url: hash:
    pkgs.stdenvNoCC.mkDerivation {
      name = "corpus-${builtins.hashString "sha256" url}";
      outputHashMode = "recursive";
      outputHashAlgo = "sha256";
      outputHash = hash;
      nativeBuildInputs = [
        corpusFetchBin
        pkgs.cacert
      ];
      SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
      buildCommand = ''
        corpus-fetch "${url}" "$out"
      '';
    };

  # Deduplicated URL → derivation map.
  urlDerivations = lib.mapAttrs fetchCorpusUrl corpusHashes;

  # Entry ID → the one file it names. Reddit gallery entries index into a
  # multi-file FOD (0, 1, 2, ...); direct URL entries always use index 0.
  #
  # Per-attribute laziness is what makes this usable on its own: a consumer that
  # names five entries realizes five FODs, where going through the link farm
  # below would realize every URL in the manifest.
  imageFiles = lib.mapAttrs (
    _id: entry: "${urlDerivations.${entry.url}}/${toString (entry.reddit_index or 0)}"
  ) corpusManifest.images;

  corpusImages = pkgs.linkFarm "chronoscope-corpus-images" (
    lib.mapAttrsToList (id: path: {
      name = id;
      inherit path;
    }) imageFiles
  );

in
{
  inherit
    corpusImages
    corpusFetchBin
    corpusManifestJson
    imageFiles
    ;
}
