name: "dinov3"
backend: "python"
max_batch_size: 1

input [
  {
    name: "images"
    data_type: TYPE_STRING
    dims: [-1]
  }
]

output [
  {
    name: "embeddings"
    data_type: TYPE_STRING
    dims: [1]
  }
]

parameters: {
  key: "image_size"
  value: { string_value: "512" }
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
