[package]
name = "chronoscope-core"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
sqlx = ["dep:sqlx"]

[dependencies]
async-lock.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
schemars.workspace = true
url.workspace = true
oxilangtag.workspace = true
unicode-normalization.workspace = true
strum.workspace = true
sha2.workspace = true
hex.workspace = true
serde_jcs.workspace = true
urlencoding = "2.1"
thiserror.workspace = true
chronoscope-macros = { path = "../chronoscope-macros" }
sqlx = { version = "0.8", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
proptest = "1.4"
tokio = { version = "1", features = ["macros", "rt"] }
