//! Identifier newtypes for the fact-store wire model.
//!
//! Two families live here:
//!
//! - **String-shaped IDs** (`EntityId`, `LifetimeEventId`, `ImageId`,
//!   `UserId`, `IngesterRunId`) share an invariant (non-empty after
//!   construction). They are generated by the [`string_id_newtype`]
//!   macro so the copies stay in lockstep.
//! - **Integer-shaped IDs** (`FactId`, `CommitId`). [`FactId`] is a
//!   thin newtype around `u64` whose only role is preventing
//!   intermixing with other integer ids. [`CommitId`] is content-addressed
//!   — derived from the commit's canonical encoding so re-submitting an
//!   identical commit yields the same id.
//!
//! [`ImageId`] identifies a *image* — a specific sequence of bytes that
//! makes up a JPEG/PNG/scan. "Image-as-pictorial-artifact" and
//! "image-as-map" are role-claims on top of an [`ImageId`], asserted via
//! `picture::Fact::IsPicture` and `map::Fact::IsMap` respectively. A
//! single [`ImageId`] can hold either role, both (rare), or neither
//! (unclassified).

use chrono::{DateTime, SubsecRound, Utc};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

// ============================================================================
// Shared error
// ============================================================================

/// Errors common to the string-shaped IDs (`EntityId`, `LifetimeEventId`,
/// `ImageId`, `UserId`, `IngesterRunId`).
///
/// All of these IDs share a single invariant — non-empty — so they share a
/// single error type. Per-id-shape distinction is conveyed through the
/// constructor's surrounding context (which type was being built).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IdError {
    /// The supplied string was empty.
    Empty,
}

impl std::fmt::Display for IdError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Empty => write!(f, "id must not be empty"),
        }
    }
}

impl std::error::Error for IdError {}

// ============================================================================
// String-ID macro
// ============================================================================

/// Emit a transparent string newtype with non-empty validation.
///
/// The generated type carries: smart constructor [`Self::new`], `as_str`,
/// `Display`, `AsRef<str>`, `TryFrom<String>`, `JsonSchema`, plus a manual
/// `Deserialize` that routes through the smart constructor so wire-level
/// empty strings are rejected at the parse boundary.
///
/// The inner `String` is sealed behind `pub(in crate::facts)` so the smart
/// constructor is the only path in from outside `crate::facts`.
#[macro_export]
macro_rules! string_id_newtype {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(
            Debug,
            Clone,
            PartialEq,
            Eq,
            PartialOrd,
            Ord,
            Hash,
            ::serde::Serialize,
            ::schemars::JsonSchema,
        )]
        #[serde(transparent)]
        pub struct $name {
            pub(in $crate::facts) inner: ::std::string::String,
        }

        impl $name {
            #[doc = "Smart constructor. Rejects empty strings."]
            pub fn new(
                id: impl ::std::convert::Into<::std::string::String>,
            ) -> ::std::result::Result<Self, $crate::facts::ids::IdError> {
                let s = id.into();
                if s.is_empty() {
                    return ::std::result::Result::Err($crate::facts::ids::IdError::Empty);
                }
                ::std::result::Result::Ok(Self { inner: s })
            }

            #[doc = "The underlying string slice."]
            #[must_use]
            pub fn as_str(&self) -> &str {
                &self.inner
            }
        }

        impl ::std::convert::TryFrom<::std::string::String> for $name {
            type Error = $crate::facts::ids::IdError;
            fn try_from(s: ::std::string::String) -> ::std::result::Result<Self, Self::Error> {
                Self::new(s)
            }
        }

        impl<'de> ::serde::Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
            where
                D: ::serde::Deserializer<'de>,
            {
                let s = <::std::string::String as ::serde::Deserialize>::deserialize(deserializer)?;
                Self::new(s).map_err(::serde::de::Error::custom)
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                ::std::fmt::Display::fmt(&self.inner, f)
            }
        }

        impl ::std::convert::AsRef<str> for $name {
            fn as_ref(&self) -> &str {
                &self.inner
            }
        }
    };
}

// ============================================================================
// Validated-string-newtype macro and shared error
// ============================================================================

/// Errors from [`validated_string_newtype`]-generated constructors.
///
/// Single shared error type so the macro doesn't have to mint a fresh
/// `<Name>Error` per invocation. Variants cover the length-bound checks
/// the macro can configure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ValidatedStringError {
    /// Trimmed length was below the configured minimum.
    TooShort {
        /// The label of the type (the macro invocation's identifier).
        type_name: &'static str,
        /// Observed character count.
        len: usize,
        /// Configured minimum.
        min: usize,
    },
    /// Length was above the configured maximum.
    TooLong {
        /// The label of the type (the macro invocation's identifier).
        type_name: &'static str,
        /// Observed character count.
        len: usize,
        /// Configured maximum.
        max: usize,
    },
}

impl std::fmt::Display for ValidatedStringError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::TooShort {
                type_name,
                len,
                min,
            } => {
                write!(f, "{type_name} too short: {len} chars (min {min})")
            }
            Self::TooLong {
                type_name,
                len,
                max,
            } => {
                write!(f, "{type_name} too long: {len} chars (max {max})")
            }
        }
    }
}

impl std::error::Error for ValidatedStringError {}

/// Emit a `#[serde(transparent)]` string newtype with length-bound
/// validation, smart constructor, `Display`, `AsRef<str>`, and manual
/// `Deserialize` that routes through the smart constructor.
///
/// Parameters:
/// - `name`: the struct identifier (also used as the human-readable
///   label in error messages).
/// - `min = N`: minimum character count after optional trimming.
///   Defaults to 0.
/// - `max = N`: maximum character count. Defaults to `usize::MAX`.
/// - `trim`: when present, the constructor trims surrounding whitespace
///   before counting characters and stores the trimmed form.
///
/// The inner `String` is sealed behind `pub(in crate::facts)` so the
/// smart constructor is the only path in from outside `crate::facts`.
#[macro_export]
macro_rules! validated_string_newtype {
    (
        $(#[$meta:meta])*
        $name:ident
        $(, min = $min:expr)?
        $(, max = $max:expr)?
        $(, trim = $trim:literal)?
        $(,)?
    ) => {
        $(#[$meta])*
        #[derive(
            ::std::fmt::Debug,
            ::std::clone::Clone,
            ::std::cmp::PartialEq,
            ::std::cmp::Eq,
            ::std::hash::Hash,
            ::serde::Serialize,
            ::schemars::JsonSchema,
        )]
        #[serde(transparent)]
        pub struct $name {
            pub(in $crate::facts) inner: ::std::string::String,
        }

        impl $name {
            const MIN_LEN: usize = $crate::__validated_string_newtype_min!($($min)?);
            const MAX_LEN: usize = $crate::__validated_string_newtype_max!($($max)?);

            #[doc = "Construct, validating length bounds (and trimming if configured)."]
            pub fn new(
                s: impl ::std::convert::AsRef<str>,
            ) -> ::std::result::Result<Self, $crate::facts::ids::ValidatedStringError> {
                let raw = s.as_ref();
                let candidate = $crate::__validated_string_newtype_maybe_trim!(raw $(, $trim)?);
                let len = candidate.chars().count();
                if len < Self::MIN_LEN {
                    return ::std::result::Result::Err(
                        $crate::facts::ids::ValidatedStringError::TooShort {
                            type_name: stringify!($name),
                            len,
                            min: Self::MIN_LEN,
                        },
                    );
                }
                if len > Self::MAX_LEN {
                    return ::std::result::Result::Err(
                        $crate::facts::ids::ValidatedStringError::TooLong {
                            type_name: stringify!($name),
                            len,
                            max: Self::MAX_LEN,
                        },
                    );
                }
                ::std::result::Result::Ok(Self {
                    inner: candidate.to_string(),
                })
            }

            #[doc = "The underlying string slice."]
            #[must_use]
            pub fn as_str(&self) -> &str {
                &self.inner
            }
        }

        impl<'de> ::serde::Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
            where
                D: ::serde::Deserializer<'de>,
            {
                let s = <::std::string::String as ::serde::Deserialize>::deserialize(deserializer)?;
                Self::new(s).map_err(::serde::de::Error::custom)
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                ::std::fmt::Display::fmt(&self.inner, f)
            }
        }

        impl ::std::convert::AsRef<str> for $name {
            fn as_ref(&self) -> &str {
                &self.inner
            }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __validated_string_newtype_min {
    () => {
        0
    };
    ($value:expr) => {
        $value
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __validated_string_newtype_max {
    () => {
        usize::MAX
    };
    ($value:expr) => {
        $value
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __validated_string_newtype_maybe_trim {
    ($s:expr) => {
        $s
    };
    ($s:expr, $do_trim:literal) => {{
        // Only the literal `true` triggers trimming; any other literal
        // is treated as a no-op so the macro stays robust to typos at
        // the call site (the test surface is mainly the SignText and
        // Justification consumers).
        if $do_trim { $s.trim() } else { $s }
    }};
}

// ============================================================================
// String IDs (macro-generated)
// ============================================================================

string_id_newtype! {
    /// Entity ID. Opaque identifier. Minted at entity-resolution time
    /// and reused for subsequent matching descriptions. Stable for the
    /// lifetime of the entity. Core treats the byte pattern as opaque;
    /// presentational layers may give it whatever shape they want.
    EntityId
}

string_id_newtype! {
    /// Lifetime-event ID. Opaque identifier for an entity-interior
    /// lifetime event (renovation, fire, repair, move, usage change,
    /// designation). Either adopted from an external system that mints
    /// event ids (e.g. Wikidata's P793 "significant event" targets) or
    /// minted fresh at ingest when the source doesn't supply one;
    /// downstream equivalence between such ids is asserted through
    /// [`crate::facts::identity::Fact::SameEvent`].
    ///
    /// Bookend life-stage facts (`Construction*`, `Demolition*`) hang
    /// directly off the entity and do not carry a `LifetimeEventId`.
    LifetimeEventId
}

string_id_newtype! {
    /// Image ID. Opaque identifier for a specific byte sequence
    /// (JPEG, PNG, scan). Minted at first ingestion via hash lookup or
    /// catalog import. Two scans of the same physical photograph have
    /// different `ImageId`s; perceptual equivalence between them is
    /// asserted via `identity::Fact::SameArtifact`.
    ///
    /// "Picture" (photograph / painting / drawing) and "map" are
    /// role-claims layered on top of an `ImageId` via
    /// `picture::Fact::IsPicture` and `map::Fact::IsMap`. The image
    /// itself doesn't carry the role at the type level — the role is a
    /// fact that can be asserted, retracted, or superseded.
    ImageId
}

string_id_newtype! {
    /// User ID for attribution. Opaque identifier minted by the
    /// auth/identity layer. Core reads it as the author of
    /// `IngestedBy::User` commits.
    UserId
}

string_id_newtype! {
    /// Ingester run ID. Opaque identifier minted at the start of an
    /// ingester run (URL worker, Wikidata pipeline, image analysis);
    /// stable for the lifetime of the run. Stored as the author of
    /// `IngestedBy::Ingester` commits.
    IngesterRunId
}

// ============================================================================
// FactId
// ============================================================================

/// Fact identifier — a typed wrapper around `u64`.
///
/// The newtype exists to prevent intermixing with other integer ids, not
/// to enforce a structural invariant: zero is a valid id and construction
/// is infallible. Pagination cursors carry `Option<FactId>` — `None` for
/// the first page, `Some` for continuations.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, JsonSchema,
)]
#[serde(transparent)]
pub struct FactId(u64);

impl FactId {
    /// Wrap a raw `u64` as a `FactId`.
    #[must_use]
    pub fn new(id: u64) -> Self {
        Self(id)
    }

    /// The underlying integer.
    #[must_use]
    pub fn get(self) -> u64 {
        self.0
    }
}

impl std::fmt::Display for FactId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}

// ============================================================================
// CommitId — content-addressed
// ============================================================================

/// A commit's hashable contents.
///
/// `Commit` is the input shape consumed by [`CommitId::from_commit`]: the
/// author, when it was recorded, and the assertions submitted together.
/// Each assertion is carried as an opaque [`serde_json::Value`] to keep
/// the type parametric in the assertion grammar — callers serialize
/// their typed assertions once before constructing the `Commit`, and the
/// same JSON representation feeds both the hash and the persisted log.
///
/// `recorded_at` is quantized to whole-second granularity before hashing
/// — sub-second jitter would otherwise defeat content addressing without
/// changing user intent.
#[derive(Debug, Clone, PartialEq)]
pub struct Commit {
    /// Canonical identity string for the commit author (e.g.
    /// `user:<UserId>` or `ingester:<IngesterRunId>`).
    pub author: String,
    /// When the commit was recorded; quantized to seconds for hashing.
    pub recorded_at: DateTime<Utc>,
    /// The assertions in the commit, each already serialized to a
    /// JSON [`Value`](serde_json::Value).
    pub assertions: Vec<serde_json::Value>,
}

impl Commit {
    /// Derive the content-addressed [`CommitId`] for this commit.
    ///
    /// Equivalent to [`CommitId::from_commit`]; lives on `Commit` so
    /// callers reach for `commit.id()` without naming the id type.
    pub fn id(&self) -> Result<CommitId, serde_json::Error> {
        CommitId::from_commit(self)
    }
}

/// Internal shape fed to JCS to derive the [`CommitId`] hash. Kept private
/// so the canonical form is fully controlled by [`CommitId::from_commit`]
/// (callers cannot rename or reorder the fields).
///
/// Field order in source does not affect the hash — JCS sorts object keys —
/// but the listed order matches the type-level doc-comment for readability.
#[derive(Serialize)]
struct CommitHashInput<'a> {
    author: &'a str,
    facts: Vec<serde_json::Value>,
    recorded_at: String,
}

/// Commit identifier — content-addressed.
///
/// The id is the lowercase-hex SHA-256 over a canonical JSON encoding of
/// the commit's contents. Identical contents produce identical ids, so a
/// retried submission of the same bundle returns the existing commit
/// rather than a duplicate.
///
/// # Canonical encoding
///
/// The canonical form is JCS (RFC 8785 JSON Canonicalization Scheme),
/// produced by the [`serde_jcs`] crate. JCS gives a single byte-for-byte
/// representation for a JSON value — object keys sorted, numbers
/// normalized, strings escaped per the spec — so independent serializers
/// agree on the bytes that get hashed.
///
/// [`CommitId::from_commit`] builds the following logical JSON document
/// and feeds the JCS encoding to SHA-256:
///
/// ```json
/// {
///   "author": "<author>",
///   "facts": [ <fact>, <fact>, ... ],
///   "recorded_at": "<rfc3339-seconds>"
/// }
/// ```
///
/// - `<author>` is the canonical form of the author identity (e.g.
///   `user:<UserId>` or `ingester:<IngesterRunId>`).
/// - `<rfc3339-seconds>` quantizes the commit time to whole-second
///   granularity. Encoded as a string rather than a chrono-typed value so
///   the wire form is fixed regardless of how `DateTime<Utc>` serializes.
/// - Each `<fact>` is one of the commit's assertions as a JSON value. The
///   facts array is sorted by each fact's own JCS encoding before
///   assembly so submission order does not perturb the id.
///
/// The hash function is full SHA-256 (no truncation); the wire shape is
/// 64 lowercase hex characters.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, JsonSchema)]
#[serde(transparent)]
pub struct CommitId {
    inner: String,
}

impl<'de> Deserialize<'de> for CommitId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        Self::parse(s).map_err(serde::de::Error::custom)
    }
}

impl CommitId {
    /// Hash-derive a `CommitId` from a structured [`Commit`].
    ///
    /// Returns an error if any individual assertion (or the assembled
    /// wrapper) fails JCS encoding. In practice JCS encoding can fail
    /// only on non-finite `f64` values inside the input — a callsite
    /// that has already validated its inputs at the grammar boundaries
    /// will see this as a `Result` it does not have to recover from.
    pub fn from_commit(commit: &Commit) -> Result<Self, serde_json::Error> {
        // Sort facts by their own JCS encoding so submission order is
        // irrelevant to the resulting id. We encode once for ordering and
        // once for the wrapper; the cost is small next to the SHA-256.
        let mut keyed: Vec<(String, &serde_json::Value)> = commit
            .assertions
            .iter()
            .map(|f| serde_jcs::to_string(f).map(|k| (k, f)))
            .collect::<Result<_, _>>()?;
        keyed.sort_by(|a, b| a.0.cmp(&b.0));
        let sorted_facts: Vec<serde_json::Value> =
            keyed.into_iter().map(|(_, f)| f.clone()).collect();

        let wrapper = CommitHashInput {
            author: &commit.author,
            facts: sorted_facts,
            recorded_at: commit.recorded_at.trunc_subsecs(0).to_rfc3339(),
        };
        let canonical = serde_jcs::to_string(&wrapper)?;

        let mut hasher = Sha256::new();
        hasher.update(canonical.as_bytes());
        Ok(Self {
            inner: hex::encode(hasher.finalize()),
        })
    }

    /// Hash-derive a `CommitId` from a commit's components.
    ///
    /// Thin convenience wrapper around [`CommitId::from_commit`] for
    /// sites that already have the three pieces but no [`Commit`] in
    /// hand.
    pub fn from_components(
        author: &str,
        recorded_at: DateTime<Utc>,
        assertions: &[serde_json::Value],
    ) -> Result<Self, serde_json::Error> {
        Self::from_commit(&Commit {
            author: author.to_string(),
            recorded_at,
            assertions: assertions.to_vec(),
        })
    }

    /// Adopt an already-validated `CommitId` string. Wire input goes
    /// through [`CommitId::try_from`] which validates length and hex
    /// shape; this entry point exists for in-crate callers that compute
    /// the id locally and want a typed wrapper without re-hashing.
    pub fn parse(id: impl Into<String>) -> Result<Self, CommitIdError> {
        let s = id.into();
        if s.len() != COMMIT_ID_HEX_LEN {
            return Err(CommitIdError::WrongLength {
                len: s.len(),
                expected: COMMIT_ID_HEX_LEN,
            });
        }
        if !s
            .bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
        {
            return Err(CommitIdError::NotLowercaseHex);
        }
        Ok(Self { inner: s })
    }

    /// The hex digest as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.inner
    }
}

impl std::convert::TryFrom<String> for CommitId {
    type Error = CommitIdError;
    fn try_from(s: String) -> Result<Self, Self::Error> {
        Self::parse(s)
    }
}

impl std::fmt::Display for CommitId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.inner, f)
    }
}

impl AsRef<str> for CommitId {
    fn as_ref(&self) -> &str {
        &self.inner
    }
}

/// Length in characters of the hex-encoded SHA-256 used for [`CommitId`].
pub const COMMIT_ID_HEX_LEN: usize = 64;

/// Errors from [`CommitId::parse`] / `TryFrom<String>`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CommitIdError {
    /// The supplied string did not have the expected hex-digest length.
    WrongLength { len: usize, expected: usize },
    /// The supplied string contained non-hex or uppercase-hex bytes.
    NotLowercaseHex,
}

impl std::fmt::Display for CommitIdError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::WrongLength { len, expected } => write!(
                f,
                "commit id has wrong length: {len} chars (expected {expected})"
            ),
            Self::NotLowercaseHex => {
                write!(f, "commit id must be lowercase hex (a-f, 0-9)")
            }
        }
    }
}

impl std::error::Error for CommitIdError {}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;
    use serde_json::json;

    type TestResult = Result<(), Box<dyn std::error::Error>>;

    #[test]
    fn entity_id_rejects_empty() {
        assert_eq!(EntityId::new(""), Err(IdError::Empty));
    }

    #[test]
    fn entity_id_deserialize_routes_through_constructor() {
        let result: Result<EntityId, _> = serde_json::from_str("\"\"");
        assert!(result.is_err(), "empty string must fail at deserialize");
    }

    fn fixed_time() -> Result<DateTime<Utc>, &'static str> {
        Utc.with_ymd_and_hms(2024, 1, 1, 12, 0, 0)
            .single()
            .ok_or("fixed timestamp is unambiguous")
    }

    fn commit(
        author: &str,
        recorded_at: DateTime<Utc>,
        assertions: Vec<serde_json::Value>,
    ) -> Commit {
        Commit {
            author: author.to_string(),
            recorded_at,
            assertions,
        }
    }

    #[test]
    fn commit_id_is_deterministic_for_same_components() -> TestResult {
        let facts = vec![json!({"kind": "a", "n": 1}), json!({"kind": "b", "n": 2})];
        let a = commit("user:alice", fixed_time()?, facts.clone()).id()?;
        let b = commit("user:alice", fixed_time()?, facts).id()?;
        assert_eq!(a, b);
        Ok(())
    }

    #[test]
    fn commit_id_is_insensitive_to_fact_order() -> TestResult {
        let a = commit(
            "user:alice",
            fixed_time()?,
            vec![json!({"kind": "a"}), json!({"kind": "b"})],
        )
        .id()?;
        let b = commit(
            "user:alice",
            fixed_time()?,
            vec![json!({"kind": "b"}), json!({"kind": "a"})],
        )
        .id()?;
        assert_eq!(a, b);
        Ok(())
    }

    /// JCS sorts object keys, so two facts that differ only in source-side
    /// key order must hash identically.
    #[test]
    fn commit_id_is_insensitive_to_object_key_order() -> TestResult {
        let a = commit(
            "user:alice",
            fixed_time()?,
            vec![json!({"alpha": 1, "beta": 2})],
        )
        .id()?;
        let b = commit(
            "user:alice",
            fixed_time()?,
            vec![json!({"beta": 2, "alpha": 1})],
        )
        .id()?;
        assert_eq!(a, b);
        Ok(())
    }

    #[test]
    fn commit_id_quantizes_subseconds() -> TestResult {
        let base = fixed_time()?;
        let with_ns = base + chrono::Duration::nanoseconds(123_456_789);
        let a = commit("user:alice", base, vec![]).id()?;
        let b = commit("user:alice", with_ns, vec![]).id()?;
        assert_eq!(a, b);
        Ok(())
    }

    #[test]
    fn commit_id_differs_for_different_authors() -> TestResult {
        let a = commit("user:alice", fixed_time()?, vec![]).id()?;
        let b = commit("user:bob", fixed_time()?, vec![]).id()?;
        assert_ne!(a, b);
        Ok(())
    }

    #[test]
    fn commit_id_parse_rejects_short() {
        assert!(matches!(
            CommitId::parse("deadbeef"),
            Err(CommitIdError::WrongLength { .. })
        ));
    }

    #[test]
    fn commit_id_parse_rejects_uppercase_hex() {
        let upper = "A".repeat(COMMIT_ID_HEX_LEN);
        assert_eq!(CommitId::parse(upper), Err(CommitIdError::NotLowercaseHex));
    }

    #[test]
    fn commit_id_parse_accepts_round_trip() -> TestResult {
        let id = commit("user:alice", fixed_time()?, vec![]).id()?;
        let parsed = CommitId::parse(id.as_str())?;
        assert_eq!(id, parsed);
        Ok(())
    }
}
