name: "sam3"
backend: "python"
max_batch_size: 1

input [
  {
    name: "image"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "prompts"
    data_type: TYPE_STRING
    dims: [-1]
    optional: true
  }
]

output [
  {
    name: "regions"
    data_type: TYPE_STRING
    dims: [1]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  },
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 1 ]
  }
]
